# Generated by Django 6.0.2 on 2026-02-19 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('youtube_url', models.URLField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('general_comment', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['-plan__date'],
                'unique_together': {('user', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('prescribed_sets', models.PositiveSmallIntegerField(default=3)),
                ('prescribed_reps', models.CharField(default='10', max_length=20)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=60)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('plan', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('reps_done', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='workouts.workoutlog')),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_logs', to='workouts.workoutplanitem')),
            ],
            options={
                'ordering': ['plan_item__order', 'set_number'],
                'unique_together': {('log', 'plan_item', 'set_number')},
            },
        ),
    ]
